// Symbols used throughout this package

// Flux actions
SMARTFORM_FORM_MOUNTED = Symbol('SMARTFORM_FORM_MOUNTED');
SMARTFORM_INPUT_MOUNTED = Symbol('SMARTFORM_INPUT_MOUNTED');
SMARTFORM_INPUT_CHANGED = Symbol('SMARTFORM_INPUT_CHANGED');
SMARTFORM_INPUT_BLURORFOCUS = Symbol('SMARTFORM_INPUT_BLURORFOCUS');

// Input field error types
ERROR_REQUIRED = Symbol('ERROR_REQUIRED');
ERROR_INVALID = Symbol('ERROR_INVALID');
ERROR_SUSPECT = Symbol('ERROR_SUSPECT');
